### ISSUE TITLE
Building error on 13.6.4

### ISSUE THREAD

**Issue by artem-s-shevchenko** [LouisBrunner/valgrind-macos#107]
### Context

I was trying to build the valgrind, but the **make** step fails. In case of installing from brew, the error is the same.

#### What went wrong?

**make** step in the process fails with the error.

> Making all in coregrind
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_amd64=1 -DVGO_darwin=1 -DVGP_amd64_darwin=1 -DVGPV_amd64_darwin_vanilla=1  -I../coregrind -DVG_LIBDIR="\"/usr/local/libexec/valgrind"\" -DVG_PLATFORM="\"amd64-darwin\""    -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/usr/include -mmacosx-version-min=10.8   -MT m_debuginfo/libcoregrind_amd64_darwin_a-debuginfo.o -MD -MP -MF m_debuginfo/.deps/libcoregrind_amd64_darwin_a-debuginfo.Tpo -c -o m_debuginfo/libcoregrind_amd64_darwin_a-debuginfo.o `test -f 'm_debuginfo/debuginfo.c' || echo './'`m_debuginfo/debuginfo.c
m_debuginfo/debuginfo.c:1945:9: error: call to undeclared function 'vgModuleLocal_is_macho_object_file'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   if (!ML_(is_macho_object_file)( (const void*) header, len ))
        ^
../include/pub_tool_basics.h:69:21: note: expanded from macro 'ML_'
#define ML_(str)    VGAPPEND(vgModuleLocal_,    str)
                    ^
../include/pub_tool_basics.h:66:29: note: expanded from macro 'VGAPPEND'
#define VGAPPEND(str1,str2) str1##str2
                            ^
<scratch space>:58:1: note: expanded from here
vgModuleLocal_is_macho_object_file
^
1 error generated.
make[3]: *** [m_debuginfo/libcoregrind_amd64_darwin_a-debuginfo.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

#### What did you expect to happen?

To build successfully.

### Information

 * macOS architecture (`uname -m`): x86_64
 * macOS version (`sw_vers`): 13.6.4
 * Xcode version (`xcrun --sdk macosx --show-sdk-version`): 14.2

**Comment by LouisBrunner** [comment]
Hey @artem-s-shevchenko,

I recently updated the `main` branch to have the latest commits from the upstream Valgrind. The CI looked good so I merged everything.

However, they were some conflicts between changes upstream and in this repo. These are now resolved and `main` should be usable again.

Sorry about that!
