### ISSUE TITLE
leak on every single simple program

### ISSUE THREAD

**Issue by dzpt** [LouisBrunner/valgrind-macos#11]
macos 10.15.2

```
#include <stdio.h>

int main()
{
    printf("123");
    return 1;
}
```

> valgrind ./t
> ==54507== Memcheck, a memory error detector
> ==54507== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==54507== Using Valgrind-3.16.0.GIT and LibVEX; rerun with -h for copyright info
> ==54507== Command: ./t
> ==54507== 
> 123==54507== 
> ==54507== HEAP SUMMARY:
> ==54507==     in use at exit: 18,425 bytes in 162 blocks
> ==54507==   total heap usage: 176 allocs, 14 frees, 23,169 bytes allocated
> ==54507== 
> ==54507== LEAK SUMMARY:
> ==54507==    definitely lost: 11,928 bytes in 127 blocks
> ==54507==    indirectly lost: 6,307 bytes in 31 blocks
> ==54507==      possibly lost: 0 bytes in 0 blocks
> ==54507==    still reachable: 190 bytes in 4 blocks
> ==54507==         suppressed: 0 bytes in 0 blocks
> ==54507== Rerun with --leak-check=full to see details of leaked memory
> ==54507== 
> ==54507== For lists of detected and suppressed errors, rerun with: -s
> ==54507== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 4 from 4)

the piece of `valgrind --leak-check=full`

> ==54577==    at 0x100110FF0: calloc (in /usr/local/Cellar/valgrind/HEAD-36f444c/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
> ==54577==    by 0x1006D8F21: initializeNonMetaClass (in /usr/lib/libobjc.A.dylib)
> ==54577==    by 0x1006D8FCB: initializeNonMetaClass (in /usr/lib/libobjc.A.dylib)
> ==54577==    by 0x1006D8FCB: initializeNonMetaClass (in /usr/lib/libobjc.A.dylib)
> ==54577==    by 0x1006C59AE: map_images_nolock (in /usr/lib/libobjc.A.dylib)
> ==54577==    by 0x1006D5512: class_addIvar (in /usr/lib/libobjc.A.dylib)
> ==54577==    by 0x1000096B6: dyld::notifyBatchPartial(dyld_image_states, bool, char const* (*)(dyld_image_states, unsigned int, dyld_image_info const*), bool, bool) (in /usr/lib/dyld)
> ==54577==    by 0x100009892: dyld::registerObjCNotifiers(void (*)(unsigned int, char const* const*, mach_header const* const*), void (*)(char const*, mach_header const*), void (*)(char const*, mach_header const*)) (in /usr/lib/dyld)
> ==54577==    by 0x1002AC801: _dyld_objc_notify_register (in /usr/lib/system/libdyld.dylib)
> ==54577==    by 0x1006C42B0: ??? (in /usr/lib/libobjc.A.dylib)
> ==54577==    by 0x100231DF1: _os_object_init (in /usr/lib/system/libdispatch.dylib)
> ==54577==    by 0x10023DF65: libdispatch_init (in /usr/lib/system/libdispatch.dylib)
> ==54577== 
> ==54577== 32 bytes in 1 blocks are definitely lost in loss record 6 of 37

**Comment by LouisBrunner** [comment]
Hi @dzpt,

Thank you for your report!
This issue should be addressed pretty soon as part of #7.
