### ISSUE TITLE
Brew upgrade not working

### ISSUE THREAD

**Issue by YsHaNgM** [LouisBrunner/valgrind-macos#12]
`brew upgrade LouisBrunner/valgrind/valgrind` only throws `Warning: louisbrunner/valgrind/valgrind HEAD-36f444c already installed`. Although exist HEAD version 3adf690 at the time point. The upgrade process can only be done by `brew reinstall valgrind`.

**Comment by LouisBrunner** [comment]
I think it depends on the Brew's cache of the latest HEAD. You can force it using `brew upgrade --fetch-HEAD LouisBrunner/valgrind/valgrind`.

I will update the README to make this clearer, thanks!
