### ISSUE TITLE
Can't install valgrind with Xcode 11.x

### ISSUE THREAD

**Issue by tknight321** [LouisBrunner/valgrind-macos#16]
Hi, I tried to install valgrind on my computer:
MacOS Cataline 10.15.6
Homebrew 2.4.9-164-gdf16e9f
Xcode 11.6

I got below error and not quite sure why

```
==> ./configure --prefix=/usr/local/Cellar/valgrind/HEAD-3ab1ae5 --enable-only64bit --build=amd64-darwin
Last 15 lines from /Users/tkishimo/Library/Logs/Homebrew/valgrind/02.configure:
checking dependency style of clang... none
checking for diff -u... yes
checking for clang option to accept ISO C99... none needed
checking for xcrun... yes
checking for Xcode SDK and includes... /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk (includes: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include)
checking for a supported version of gcc... ok (Apple LLVM version 11.0.3)
checking build system type... x86_64-pc-darwin
checking host system type... x86_64-pc-darwin
checking for a supported CPU... ok (x86_64)
checking for a 64-bit only build... yes
checking for a 32-bit only build... no
checking for a supported OS... ok (darwin)
checking for the kernel version... Darwin 19.x (19.6.0) / macOS 10.15 Catalina
checking for the Xcode SDK version... unsupported (11.0)
configure: error: Valgrind works on Darwin 10.x-19.x (Mac OS X 10.6-11 and macOS 10.12-15)
```

Should I downgrade XCode to ver 11.0?
Any help would be really appreciated.

**Comment by LouisBrunner** [comment]
I just tried with `10.15.4` and it builds, if there any newer Xcode for `10.15` they probably should work too (`11.0` is definitely unsupported at the moment).

**Comment by vamsikt** [comment]
when tried using the `10.X Xcode version` on MacOSX version `10.15.6`, got an Xcode outdated version error but with Xcode 11 seeing the above error as mentioned in [issue](https://github.com/LouisBrunner/valgrind-macos/issues/16#issue-693347587)
```
HEAD is now at e0af3eb59 Merge branch 'development'
Error: Your Xcode (10.3 => /Users/vamsitatikonda/Downloads/Xcode.app/Contents/Developer) is too outdated.
Please update to Xcode 11.5 (or delete it).
Xcode can be updated from the App Store.
```

**Comment by LouisBrunner** [comment]
I'll try to get Xcode `11.X` this week and update the build script, I will keep you up to date.

**Comment by LouisBrunner** [comment]
@vamsikt, How did you install Xcode? I updated to 10.15.6 with the matching Xcode 11.7 and I still get a SDK version of 10.15.6

**Comment by LouisBrunner** [comment]
I finally managed through downloading a beta version of Xcode 12. I just pushed the fix on `master`, feel free to upgrade `valgrind` and check.

**Comment by vamsikt** [comment]
@LouisBrunner thank you, I was able to upgrade and install now.
