### ISSUE TITLE
not compiling with xcode 12.1 and command line tools 12 

### ISSUE THREAD

**Issue by windev92** [LouisBrunner/valgrind-macos#20]
cd valgrind-macos
./autogen.sh
./configure --prefix=/where/you/want/it/installed --enable-only64bit
make 
sudo make install

/usr/local/bin/mpicc    -I../include  -g -O -fno-omit-frame-pointer -Wall -dynamic -arch x86_64 -Wno-deprecated-declarations  -MT libmpiwrap_amd64_darwin_so-libmpiwrap.o -MD -MP -MF .deps/libmpiwrap_amd64_darwin_so-libmpiwrap.Tpo -c -o libmpiwrap_amd64_darwin_so-libmpiwrap.o `test -f 'libmpiwrap.c' || echo './'`libmpiwrap.c
libmpiwrap.c:281:19: error: expected ')'
   else if (ty == MPI_UB)             fprintf(f,"UB");

**Comment by langmm** [comment]
This seems to be fixed when using the patch [here](https://bugs.kde.org/show_bug.cgi?id=401416#c3) that removes the use of deprecated MPI symbols (I don't know if there are replacement symbols that should be added to replace the removed lines). I have implemented this patch on my [fork](https://github.com/LouisBrunner/valgrind-macos/compare/master...langmm:master) (it also includes the addition of a handler for the mkdirat syscall which causes valgrind to fail when used for R). 

It seems this might be fixed upstream at some point, but I can create a PR here if desired.

**Comment by LouisBrunner** [comment]
@windev92,
Which version of macOS were you using?

**Comment by windev92** [comment]
bigsur
________________________________

**Comment by LouisBrunner** [comment]
Looks like this has been fixed upstream, so I am closing this.

@langmm I think mkdirat has been added a while back (I will do a second pass to be sure) but feel free to open a PR if there is anything you are missing.
