### ISSUE TITLE
Valgrind detected no leak?

### ISSUE THREAD

**Issue by anta40** [LouisBrunner/valgrind-macos#22]
Hi, just updated my Mac to BigSur.

I have gcc 11 installed via homebrew:

> gcc-HEAD --version
> gcc-HEAD (Homebrew GCC HEAD-6c2675f) 11.0.0 20201002 (experimental)
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

And also valgrind:

> valgrind --version
> valgrind-3.17.0.GIT-lbmacos

Let's try this C code (taken from [here](http://cs.ecs.baylor.edu/~donahoo/tools/valgrind/)). First, compile:

> gcc-HEAD -g vtest1.c -o vtest

Then let valgrind do the work:

> valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes -s ./vtest1 

The output is:

> ==14873== Memcheck, a memory error detector
> ==14873== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
> ==14873== Using Valgrind-3.17.0.GIT-lbmacos and LibVEX; rerun with -h for copyright info
> ==14873== Command: ./vtest1
> ==14873== 
> ==14873== Warning: set address range perms: large range [0x7fff2002b000, 0x80001fe2b000) (defined)
> ==14873== Warning: set address range perms: large range [0x7fff2002b000, 0x7fff7ffeb000) (defined)
> ==14873== Warning: set address range perms: large range [0x7fff8e5a3000, 0x7fffc002b000) (noaccess)
> ==14873== Warning: set address range perms: large range [0x7fffc002b000, 0x7fffe1d13000) (defined)
> ==14873== Warning: set address range perms: large range [0x7fffe1d13000, 0x7fffffe00000) (noaccess)
> ==14873== 
> ==14873== FILE DESCRIPTORS: 3 open at exit.
> ==14873== Open file descriptor 2: /dev/ttys000
> ==14873==    <inherited from parent>
> ==14873== 
> ==14873== Open file descriptor 1: /dev/ttys000
> ==14873==    <inherited from parent>
> ==14873== 
> ==14873== Open file descriptor 0: /dev/ttys000
> ==14873==    <inherited from parent>
> ==14873== 
> ==14873== 
> ==14873== HEAP SUMMARY:
> ==14873==     in use at exit: 0 bytes in 0 blocks
> ==14873==   total heap usage: 0 allocs, 0 frees, 0 bytes allocated
> ==14873== 
> ==14873== All heap blocks were freed -- no leaks are possible
> ==14873== 
> ==14873== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

I don't see any line mentioning leaks or statictics like shown in the link above.

**Comment by LouisBrunner** [comment]
Hi @anta40,

Big Sur support is currently experimental, please refer to #19 for more information.

**Comment by anta40** [comment]
Ah very well. I guess I'll have to switch to Linux for this purpose.
