### ISSUE TITLE
`make` fails on 10.14.6 ("has __UNIXSTACK, but wrong ::maxprot (should be 7)")

### ISSUE THREAD

**Issue by dominiquelee** [LouisBrunner/valgrind-macos#3]
On a Mojave 10.14.6, building the current master (https://github.com/LouisBrunner/valgrind-macos/commit/a8e287909c049c04a388b45cc8ae22d0750ad2ea) with
```
./autogen.sh 
./configure --prefix=/usr/local/valgrind/bin --enable-only64bit
make
```
results in
```
Making all in memcheck
Making all in .
../coregrind/link_tool_exe_darwin 0x158000000 gcc     -o memcheck-amd64-darwin   -arch x86_64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare -mmacosx-version-min=10.6 -O2 -nodefaultlibs -nostartfiles -Wl,-u,__start -Wl,-e,__start -arch x86_64 memcheck_amd64_darwin-mc_leakcheck.o memcheck_amd64_darwin-mc_malloc_wrappers.o memcheck_amd64_darwin-mc_main.o memcheck_amd64_darwin-mc_main_asm.o memcheck_amd64_darwin-mc_translate.o memcheck_amd64_darwin-mc_machine.o memcheck_amd64_darwin-mc_errors.o ../coregrind/libcoregrind-amd64-darwin.a ../VEX/libvex-amd64-darwin.a -lgcc 
link_tool_exe_darwin: /usr/bin/ld -static -arch x86_64 -macosx_version_min 10.6 -o memcheck-amd64-darwin -u __start -e __start -image_base 0x158000000 -stack_addr 0x154000000 -stack_size 0x800000 memcheck_amd64_darwin-mc_leakcheck.o memcheck_amd64_darwin-mc_malloc_wrappers.o memcheck_amd64_darwin-mc_main.o memcheck_amd64_darwin-mc_main_asm.o memcheck_amd64_darwin-mc_translate.o memcheck_amd64_darwin-mc_machine.o memcheck_amd64_darwin-mc_errors.o ../coregrind/libcoregrind-amd64-darwin.a ../VEX/libvex-amd64-darwin.a
link_tool_exe_darwin: ../coregrind/fixup_macho_loadcmds 0x154000000 0x800000 memcheck-amd64-darwin
fixup_macho_loadcmds: requested stack_addr (top) 0x154000000, stack_size 0x800000
fixup_macho_loadcmds: examining tool exe: memcheck-amd64-darwin
fixup_macho_loadcmds:   initial RSP is as expected (0x154000000)
fixup_macho_loadcmds: fail: has __UNIXSTACK, but wrong ::maxprot (should be 7)
make[3]: *** [memcheck-amd64-darwin] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by LouisBrunner** [comment]
@dominiquelee, thanks for your report, it was reported on the bugtracker (https://bugs.kde.org/show_bug.cgi?id=399584) but it might be easier to debug here.

I am using 10.14.6 as well and I don't get this issue. The problem should be fairly easy to fix but I want to be sure of what is going on.

Could you please paste the output of `./configure`?

**Comment by dominiquelee** [comment]
Sure.
`./configure --prefix=/usr/local/valgrind/bin --enable-only64bit`
[configureOutput.txt](https://github.com/LouisBrunner/valgrind-macos/files/4212742/configureOutput.txt)

**Comment by LouisBrunner** [comment]
Thanks, it is what I thought. I am finalising some other work and I will get on right after.

**Comment by LouisBrunner** [comment]
Could you try the [feature/xcode_check](https://github.com/LouisBrunner/valgrind-macos/tree/feature/xcode_check) branch?

**Comment by Akylzhan** [comment]
@LouisBrunner , I have another error, even with **xcode_check** branch
`Making all in coregrind
(cd m_mach && mig /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/mach_vm.defs /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/task.defs /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/thread_act.defs /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/vm_map.defs)
"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/task.defs", line 509: type 'task_exc_guard_behavior_t' not defined
mig: fatal: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/task.defs", line 509: 1 errors found. Abort.

make[2]: *** [m_mach/mach_vmUser.c] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2`

Here is the output of `./configure` command:
[configure_output.txt](https://github.com/LouisBrunner/valgrind-macos/files/4217201/configure_output.txt)

**Comment by dominiquelee** [comment]
On my side, it's indeed working fine. I guess it's worth adding I have Xcode 11.3.1 (11C504).
Thanks for the debugging!

**Comment by LouisBrunner** [comment]
@dominiquelee, thanks for the confirmation!

@Akylzhan, I have run into a similar issue before, I think it was linked to a setup issue.
Can you check if `/usr/include/mach/` still exist on your system?
If you could run `env` and post the result, that might also be helpful.
Moreover, looking at your `configure` output, it seems to be picking up `gcc-9` instead of `clang` (as it seems like it is coming from brew, you can do `brew unlink gcc` while configuring and then `brew link gcc` to restore to the previous setup).

**Comment by Akylzhan** [comment]
There is no such directory
Output of env:
```TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/5y/wfg26j6x6s3cgb3rw0l_lpsh0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.pq6n7rf0Jx/Render
TERM_PROGRAM_VERSION=421.2
OLDPWD=/Users/akylzhansauranbay
TERM_SESSION_ID=E09A1988-6175-487D-8754-7F8AC75A10AC
USER=akylzhansauranbay
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.8NmLNatxgp/Listeners
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
HOMEBREW_EDITOR=/usr/bin/vim
PWD=/usr
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/akylzhansauranbay
LOGNAME=akylzhansauranbay
LC_CTYPE=UTF-8
_=/usr/bin/env```

**Comment by LouisBrunner** [comment]
@Akylzhan, let's try the gcc route then. I forgot that you don't need to disable/remove your extra gcc, you can just force `configure` to find the right one, just run `CC=/usr/bin/gcc ./configure`

**Comment by Akylzhan** [comment]
@LouisBrunner the same error occurred

**Comment by LouisBrunner** [comment]
@Akylzhan I'll need the `configure` output again to know what is going on

**Comment by Akylzhan** [comment]
@LouisBrunner thanks for the support, now I have tried to install it again and valgrind installs with brew, but the new problem occurred when I used valgrind to check for mem.leaks in empty c++ executable and it shows many definitely lost leaks

**Comment by LouisBrunner** [comment]
@Akylzhan That's a different problem, please create a new issue including the output of valgrind, what was expected, etc.
