### ISSUE TITLE
MacOS 11.2.1 - Error while installing with HomeBrew

### ISSUE THREAD

**Issue by natjacques** [LouisBrunner/valgrind-macos#30]
Hello there,

After a while googling and so, I can't achieve the installation with HomeBrew. I get the same error whatever I try.
Following the instructions given, everything goes well until the "make" (see console bellow).

Any idea? I don't think it's about the same matter as the already opened issue about BigSur so I created a new one.

Many thanks !!

`natjacques@MacBook-Pro-de-Nathan ~ % brew tap LouisBrunner/valgrind
natjacques@MacBook-Pro-de-Nathan ~ % brew install --HEAD LouisBrunner/valgrind/valgrind
==> Installing valgrind from louisbrunner/valgrind
==> Cloning https://github.com/LouisBrunner/valgrind-macos.git
Updating /Users/natjacques/Library/Caches/Homebrew/valgrind--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at adaae87 Merge branch 'development'
==> ./autogen.sh
==> ./configure --prefix=/opt/homebrew/Cellar/valgrind/HEAD-adaae87 --enable-onl
==> make
Last 15 lines from /Users/natjacques/Library/Logs/Homebrew/valgrind/03.make:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach/i386/thread_status.h:254:9: error: unknown type name '_STRUCT_X86_DEBUG_STATE64'
typedef _STRUCT_X86_DEBUG_STATE64 x86_debug_state64_t;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach/i386/thread_status.h:260:9: error: unknown type name '_STRUCT_X86_PAGEIN_STATE'
typedef _STRUCT_X86_PAGEIN_STATE x86_pagein_state_t;
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/mach/i386/thread_status.h:266:9: error: unknown type name '_STRUCT_X86_INSTRUCTION_STATE'
typedef _STRUCT_X86_INSTRUCTION_STATE x86_instruction_state_t;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [fixup_macho_loadcmds] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.`

**Comment by Gerzer** [comment]
Does your MacBook Pro use Apple silicon, or does it have an Intel processor? I don't think that Valgrind runs at all on Apple silicon yet.

**Comment by LouisBrunner** [comment]
@Gerzer is right, M1 is not supported and neither is Big Sur unfortunately (#19)

**Comment by natjacques** [comment]
Yes I am on Apple M1 chip processor. Thank you anyways!
Do you know any alternative for valgrind though?

**Comment by LouisBrunner** [comment]
@natjacques Some people have posted recommendations in #19, I personally don't have experience with any outside of Valgrind.
