### ISSUE TITLE
Failure on Tcl

### ISSUE THREAD

**Issue by dkfellows** [LouisBrunner/valgrind-macos#36]
When running valgrind on [tclsh](/tcltk/tcl) (trying to analyse whether I've got some code right that I'm working on) I get this:

    --42281-- WARNING: unhandled amd64-darwin syscall: unix:228

According to [this](/apple/darwin-xnu/blob/main/bsd/kern/syscalls.master), that's the `fgetattrlist()` system call. It'd be nice if this worked. (I can't identify what code is actually calling that; it's nothing direct.)

**Comment by LouisBrunner** [comment]
Hi @dkfellows,

Thanks for your report, that should be an easy fix (hopefully!)
