### ISSUE TITLE
unhandled amd64-darwin syscall: unix:464

### ISSUE THREAD

**Issue by dscho** [LouisBrunner/valgrind-macos#38]
When I tried to [use this in a GitHub workflow](https://github.com/dscho/git/runs/2998707603?check_suite_focus=true#step:5:63), I was greeted with this error:

> WARNING: unhandled amd64-darwin syscall: unix:464

A quick web search suggests that the bug was already logged at https://bugs.kde.org/show_bug.cgi?id=390269 and that the root cause is that the `openat_nocancel()` syscall is not handled. However, there seems to be no movement on that ticket over the past 3 years.

Any guidance how I could fix this real quick?

**Comment by LouisBrunner** [comment]
Hi @dscho,

Thanks for the report, this should be an easy fix (hopefully!)

No guarantee you won't run into other issues though!

**Comment by dscho** [comment]
> this should be an easy fix (hopefully!)

Do you think I could help? If you give me any pointers, I could try to find some time tomorrow to work on it.

**Comment by LouisBrunner** [comment]
You can try for sure, here are the key elements:

* Add a define for the syscall in https://github.com/LouisBrunner/valgrind-macos/blob/master/include/vki/vki-scnums-darwin.h#L782 (gated behind 10_15 or 11_00, whichever you use)
* Declare the handler in https://github.com/LouisBrunner/valgrind-macos/blob/master/coregrind/m_syswrap/priv_syswrap-darwin.h#L580 (same ifndef)
* Register the handler in https://github.com/LouisBrunner/valgrind-macos/blob/master/coregrind/m_syswrap/syswrap-darwin.c#L11276 (same ifndef, probably a `MACXY`)
* Finally implement the handler in https://github.com/LouisBrunner/valgrind-macos/blob/master/coregrind/m_syswrap/syswrap-darwin.c#L10724 (same block as the ifndef), this includes the extra checks that the syscall is correctly called (e.g. with `openat` which you can probably copy as-is https://github.com/LouisBrunner/valgrind-macos/blob/master/coregrind/m_syswrap/syswrap-darwin.c#L10084)

That should be it! (I will add a comment if I remember something else)
Feel free to ask any questions and I'll answer the best I can.

Don't hesitate to tell me if you can't figure it out and I'll try to find time to do it this weekend.

**Comment by dscho** [comment]
Thank you! And sorry for not getting around to try to fix this myself...

**Comment by LouisBrunner** [comment]
No worries, it's an easy fix ;)
