### ISSUE TITLE
Doesn't show the line where memory has been leaked

### ISSUE THREAD

**Issue by Franco-Losardo** [LouisBrunner/valgrind-macos#43]
I have MacOS catalina 10.15.7, and xcode 12.4 installed. Whenever I have some kind of memory leak, valgrind doesn't show me the line where the leak was found. Example: 
```c++
int main(){
int* p = new int[5];
cout << *p << endl;
return 0;
}
```

It should return somthing like `-Error type- by -memory address-: main line 2...`. And for this example what I get is the following picture(executed valgrind with the following flags: `valgrind --leak-check=full --track-origins=yes --show-reachable=yes ./progam_name`) No matter what flags i run valgrind with, it never shows me the line where the leak was found:

![Screenshot 2021-09-21 at 14 51 32](https://user-images.githubusercontent.com/61808560/134222197-e90d02af-ed16-410e-8ba4-0fd81cee65b8.png)

I hope I explained myself.

**Comment by Franco-Losardo** [comment]
Fixed! I use the old but very reliable method of uninstalling and installing again valgrind, and now works. It does show me the line where memory was asked for. I also updated homebrew so it must have been something related to valgrind and/or homebrew. Thank you Louis for making valgrind compatible with catalina 😀 !!

**Comment by LouisBrunner** [comment]
Hi @Franco-Losardo,

I am happy to hear that you fixed your issue!

For future reference, it looks like it could be linked to you compiling your program (`programa`) without `-g` to include debug information.
