### ISSUE TITLE
Missing symbols for _mig_strncpy[_zerofill]

### ISSUE THREAD

**Issue by jpflori** [LouisBrunner/valgrind-macos#5]
On my computer, using 10.15.4, make fails at the linking stage complaining about missing symbols _mig_strncpy[_zerofill].
Simply putting the implementation from 
https://github.com/apple/darwin-xnu/blob/master/libsyscall/mach/mig_strncpy.c
into a mach_strncpy.c file in coregrind/m_mach/ and adding it to the build process seems to work, e.g. with patch below.
Maybe stubs would be enough, I have no idea.
 
[mach_strncpy.diff.txt](https://github.com/LouisBrunner/valgrind-macos/files/4470427/mach_strncpy.diff.txt)

**Comment by find1dream** [comment]
Thanks, I'm also using macOS 10.15.4, and used the method mentioned above, it works.

**Comment by LouisBrunner** [comment]
Hi @jpflori, thanks for your report!

I have now fixed that issue, I am trying to sort out some issues with the CI right now and I will push something on master soon.

However I don't think importing the file is possible. XNU is licensed as APSL (Apple Public Source License v2) which seems incompatible with GPL (license used by Valgrind), so I did a "clean room implementation" based on the header of the file.

**Comment by jlouazel** [comment]
Hi @jpflori, thanks for the help!

I am running on 10.15.3 here, and I'm getting an error due to missing magic number here: https://github.com/LouisBrunner/valgrind-macos/blob/master/coregrind/m_syswrap/syswrap-x86-darwin.c#L428-L434

Seems like `10_15` is not present there. Wondering still why you didn't get the issue on your side 🤔

**Comment by LouisBrunner** [comment]
@jlouazel Work Queue Threads (wqthread) are unsupported at the moment (see #4).

**Comment by LouisBrunner** [comment]
I have now merged the fix to `master`, can you please confirm it is building and working as expected?

**Comment by jpflori** [comment]
Works great. Thx.
