### ISSUE TITLE
Ventura (macOS 13.0) compatibility

### ISSUE THREAD

**Issue by MalwarePup** [LouisBrunner/valgrind-macos#54]
Hello,

Following the issues #19 and #44 same error on macOS 13.0.

`configure: error: Valgrind works on Darwin 10.x-20.x (Mac OS X 10.6-10.11 and macOS 10.12-11.0)`

**Comment by DevRadion** [comment]
same problem(

**Comment by luowencai** [comment]
same

**Comment by LouisBrunner** [comment]
Valgrind now _builds_ on macOS 13, but unfortunately (#59), it is still not _running_ properly.

I will be tracking the progress around this in the above issue.

**Comment by LouisBrunner** [comment]
As an update, Valgrind is now working properly on macOS 13 (amd64). M1 support is in progress but might take a while (#56).

**Comment by MalwarePup** [comment]
> As an update, Valgrind is now working properly on macOS 13 (amd64). M1 support is in progress but might take a while (#56).

Thank you for the update and the work !
