### ISSUE TITLE
m2 air error 

### ISSUE THREAD

**Issue by huangfeifan** [LouisBrunner/valgrind-macos#57]
huangff@192 ~ % install --HEAD LouisBrunner/valgrind/valgrind
install: illegal option -- -
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
huangff@192 ~ % brew install --HEAD LouisBrunner/valgrind/valgrind 
==> Cloning https://github.com/LouisBrunner/valgrind-macos.git
Updating /Users/huangff/Library/Caches/Homebrew/valgrind--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 59136a186 fix(macos): improve GH CI
==> Installing valgrind from louisbrunner/valgrind
==> ./autogen.sh
==> ./configure --prefix=/opt/homebrew/Cellar/valgrind/HEAD-59136a1 --enable-only64bit --build=amd64-darwin
==> make
Last 15 lines from /Users/huangff/Library/Logs/Homebrew/valgrind/03.make:
fixup_macho_loadcmds.c:465:22: error: use of undeclared identifier 'x86_thread_state64_t'
                  = (x86_thread_state64_t*)(&w32s[2]);
                     ^
fixup_macho_loadcmds.c:467:36: error: no member named '__rsp' in 'struct __darwin_arm_thread_state64'; did you mean '__sp'?
               init_rsp = state64->__rsp;
                                   ^~~~~
                                   __sp
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/mach/arm/_structs.h:141:13: note: '__sp' declared here
        __uint64_t __sp;    /* Stack pointer x31 */
                   ^
7 errors generated.
make[2]: *** [fixup_macho_loadcmds] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

valgrind's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
huangff@192 ~ %

**Comment by cmplsn** [comment]
just received the same error on m1 Air

**Comment by LouisBrunner** [comment]
Hi @huangfeifan and @cmplsn,

Apple Silicon is currently unsupported, I will be tracking the progress as part of #56.
