### ISSUE TITLE
Let's make Valgrind run on macOS 13 / m1

### ISSUE THREAD

**Issue by edsiper** [LouisBrunner/valgrind-macos#58]
hi, 

I think Valgrind is such a great tool but the lack of constant support for macOS 13 adds a lot of complications. 

Our company, would be happy to sponsor the work to get running binaries for macOS Ventura. Please DM me to discuss details: eduardo at calyptia dot com.

**Comment by LouisBrunner** [comment]
Hi @edsiper,

I have now setup a GitHub Sponsors ([here](https://github.com/sponsors/LouisBrunner)) if you want to help sponsor the project.

This would definitely help me improve the support for macOS 11 and later!
