### ISSUE TITLE
Valgrind ends instantly

### ISSUE THREAD

**Issue by Lazarus404** [LouisBrunner/valgrind-macos#59]
Valgrind has installed successfully (at least, no errors were present), but when I run it, it kills without outputting anything.  Thus

`valgrind ls -l`

ends with

`zsh: killed     valgrind ls -l`

If I run valgrind against a compiled C++ app, the same thing happens.

**Comment by Lazarus404** [comment]
When `make'ing, I do see a lot of
```
libcoregrind_amd64_darwin_a-dispatch-x86-solaris.o)) was built for newer macOS version (13.0) than being linked (10.6)
```
etc.

**Comment by LouisBrunner** [comment]
Hey @Lazarus404,

Thanks for the report, valgrind currently has a crash on start up on macOS 13. I am still working through a fix for it.

**Comment by LouisBrunner** [comment]
This issue should now be resolved.
