### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by dreamflyforever** [LouisBrunner/valgrind-macos#61]
fixup_macho_loadcmds.c:112:4: error: "Can't be compiled on this platform"
  error "Can't be compiled on this platform"
   ^
fixup_macho_loadcmds.c:308:14: error: "unknown architecture"
            error "unknown architecture"

target: m2 MacBook
build mother: make

**Comment by LouisBrunner** [comment]
M1/M2 is currently unsupported (#56)
