### ISSUE TITLE
Warnings with every piece of test

### ISSUE THREAD

**Issue by sweetodev** [LouisBrunner/valgrind-macos#7]
These set of 3 warnings are repeatedly coming across on Catalina while running valgrind. 

Same set of code was tested on Ubuntu without any errors, so I'm sure it's not the code and something else. 

Here's a screenshot.  https://i.stack.imgur.com/hJkAF.png

**Comment by LouisBrunner** [comment]
I have added more suppressions which should hide these leaks, these changes are available in `master` (and thus through `brew`).
