### ISSUE TITLE
Build failed when attempting to install from HEAD on MacStudio M1 ultra, Ventura OS

### ISSUE THREAD

**Issue by alfishe** [LouisBrunner/valgrind-macos#84]
### Context

Build failed when attempting to install from HEAD on MacStudio M1 ultra, Ventura OS

#### What went wrong?

brew install --HEAD LouisBrunner/valgrind/valgrind
==> Fetching louisbrunner/valgrind/valgrind
==> Cloning https://github.com/LouisBrunner/valgrind-macos.git
Cloning into '/Users/dev/Library/Caches/Homebrew/valgrind--git'...
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
==> Installing valgrind from louisbrunner/valgrind
==> ./autogen.sh
==> ./configure --prefix=/opt/homebrew/Cellar/valgrind/HEAD-73c9e41 --enable-only64bit --build=amd64-darwin
==> make
Last 15 lines from /Users/dev/Library/Logs/Homebrew/valgrind/03.make:
fixup_macho_loadcmds.c:465:22: error: use of undeclared identifier 'x86_thread_state64_t'
                  = (x86_thread_state64_t*)(&w32s[2]);
                     ^
fixup_macho_loadcmds.c:467:36: error: no member named '__rsp' in 'struct __darwin_arm_thread_state64'; did you mean '__sp'?
               init_rsp = state64->__rsp;
                                   ^~~~~
                                   __sp
/Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/usr/include/mach/arm/_structs.h:141:13: note: '__sp' declared here
        __uint64_t __sp;    /* Stack pointer x31 */
                   ^
7 errors generated.
make[2]: *** [fixup_macho_loadcmds] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

#### What did you expect to happen?

Build successfully finished and cask installed

### Information

 * macOS architecture (`uname -m`): arm64
 * macOS version (`sw_vers`): 13.4
 * Xcode version (`xcrun --sdk macosx --show-sdk-version`): 13.3

**Comment by alfishe** [comment]
My fault - didn't check official compatibility list, but platform detection definitely needs to be fixed...

**Comment by LouisBrunner** [comment]
Hey @alfishe,

Good point, the formula was a bit old so I upgraded it https://github.com/LouisBrunner/homebrew-valgrind/pull/16

See #56 for updates about Apple Silicon support.
