### ISSUE TITLE
Syntax error in cg_annotate

### ISSUE THREAD

**Issue by dasfex** [LouisBrunner/valgrind-macos#89]
### Context

Hey. I recently tried to use your cachegrind. I get some cachegrind.out file. Next I tried to use cg_annotate on this file but get an error. 

#### What went wrong?

command: 
```
cg_annotate cachegrind.out
```
result
```
  File "/usr/local/bin/cg_annotate", line 449
    while line := readline():
                ^
SyntaxError: invalid syntax
```
And I get this error even on 
```
cg_annotation --version
```

### Information

 * macOS architecture (`uname -m`): x86_64
 * macOS version (`sw_vers`): 12.1
 * Xcode version (`xcrun --sdk macosx --show-sdk-version`): 12.3

**Comment by paulfloyd** [comment]
What is the shebang line on that file?

I'm not too familiar with macports - the FreeBSD ports system uses a shebangfix tool to ensure that the installed scripts always use a known working version of Python (or Perl)

**Comment by dasfex** [comment]
Thanks a lot. My local python3 was python3.7.
