### ISSUE TITLE
Running into error "UNKNOWN workq_ops option 1024" when running

### ISSUE THREAD

**Issue by Sokkero** [LouisBrunner/valgrind-macos#95]
Running 
`valgrind --tool=memcheck --xml=yes --xml-file=/private/var/folders/6m/wmpj6b6x4wv4tg4m65pz2wrr0000gp/T/clion-valgrind2cbebd68-1028-4aa2-84ac-a18d257e6808/valgrind_output_%p --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no /Volumes/privateWorkspace/projects/cpp/openGL/engine-0.2/cmake-build-debug/bin/openGLTutorial` 
within Clion grants me the error message:
```
UNKNOWN workq_ops option 1024
==76044==  If you believe this happened as a result of a stack
==76044==  overflow in your program's main thread (unlikely but
==76044==  possible), you can try to increase the size of the
==76044==  main thread stack using the --main-stacksize= flag.
==76044==  The main thread stack size used in this run was 8388608.

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```
My CMakeLists.txt is:
```
cmake_minimum_required(VERSION 3.24)

set(CMAKE_BUILD_TYPE Debug)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(PROJECT_NAME "openGLTutorial")
set(SHADER_DIR ${CMAKE_BINARY_DIR}/src/shaders)
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fsanitize=undefined -g")

project(${PROJECT_NAME})

find_package(OpenGL REQUIRED)

if(EXISTS ${CMAKE_BINARY_DIR}/conanBuild/conanbuildinfo.cmake)
    include(${CMAKE_BINARY_DIR}/conanBuild/conanbuildinfo.cmake)
    conan_basic_setup()
else()
    message(WARNING "The file conanbuildinfo.cmake doesn't exist, you have to run ./build.sh first")
endif()

FILE(GLOB_RECURSE SOURCE_FILES src/*.cpp src/*.h)
add_executable(${PROJECT_NAME} ${SOURCE_FILES} ${RES_FILES} main.cpp)

# Copy src/resources -> bin/resources
file(COPY ${CMAKE_SOURCE_DIR}/src/resources DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/bin)

target_link_libraries(${PROJECT_NAME} ${CONAN_LIBS})
```
Not sure what causes this error as another project (very simple test project) runs fine using Valgrind.

Using MacOS Ventura 13.1

**Comment by LouisBrunner** [comment]
Hi @Sokkero,

From the fact you use OpenGL, I imagine that your program creates some kind of window? Valgrind currently doesn't support GUI programs (see #4) as the wqthread is not supported correctly.

It's difficult to say more without actually being able to run/see the code. Does your other project also have a GUI?

**Comment by Sokkero** [comment]
Hello @LouisBrunner, 
thank you for the response. I was not aware that Valgrind doesnt support GUI programs, my apologies.
This explains why my openGL project fails to run valgrind whilst the simple test project doesnt.

Thank you for you help 🙏🏻
