### ISSUE TITLE
Allow building with XCode 15

### ISSUE THREAD

**Issue by rsmz** [LouisBrunner/valgrind-macos#97]
I was updating to XCode 14.3 in the AppStore and it decided to immediately update to XCode 15 released yesterday, so I thought I'd try anyway and it fails to build.

$ clang --version
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: x86_64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ brew install --HEAD LouisBrunner/valgrind/valgrind
checking for Xcode SDK and includes... /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk (includes: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include)
checking for a supported version of gcc... ok (Apple LLVM version 15.0.0)
checking build system type... x86_64-apple-darwin22.6.0
checking host system type... x86_64-apple-darwin22.6.0
checking for a supported CPU... ok (x86_64)
checking for a 64-bit only build... no
checking for a 32-bit only build... no
checking for a supported OS... ok (darwin22.6.0)
checking for the kernel version... Darwin 22.x (22.6.0) / macOS 13 Ventura
checking for the Xcode SDK version... unsupported (14.0)
configure: error: Valgrind works on Darwin 10.x-22.x (Mac OS X 10.6-11 and macOS 10.12-13.0)

**Comment by paulfloyd** [comment]
See these changes to configure.ac
https://github.com/paulfloyd/macos_valgrind/commit/097ed5d3b1437943a1da79ea5f6b98e68212815c

Ignore the changes to VG_(di_load_di)( DebugInfo *di )
They are required for the latest upstream code.

**Comment by audio-engineer** [comment]
@paulfloyd Why don't you open a pull request to this repository so that all users of `brew` that run the latest macOS/XCode versions can install `valgrind`?

**Comment by paulfloyd** [comment]
Lack of time mainly. My priorities are FreeBSD, upstream bug fixes and features, Illumos and macOS more or less in that order. Also I'd prefer even more to get the code merged upstream.

**Comment by LouisBrunner** [comment]
Hi,

> I was updating to XCode 14.3 in the AppStore and it decided to immediately update to XCode 15 released yesterday, so I thought I'd try anyway and it fails to build.

I was waiting for Sonoma to come out, but I didn't realize it came out last month. Just merged the latest upstream change and macOS 14 support into `main`.

> Also I'd prefer even more to get the code merged upstream.

That would be great!

**Comment by jonhoo** [comment]
@LouisBrunner I found this issue after wondering whether Sonoma was supported and not seeing it in the table in the README. If it is indeed now supported, may be good to add it to the list!

**Comment by LouisBrunner** [comment]
> @LouisBrunner I found this issue after wondering whether Sonoma was supported and not seeing it in the table in the README. If it is indeed now supported, may be good to add it to the list!

Good point, done!
